FROM node:9.11.1
LABEL maintainers="Stefano Fioravanzo <fioravanzo@fbk.eu>"

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY public /usr/src/app/public
COPY src /usr/src/app/src
COPY package.json /usr/src/app/package.json
#COPY package-lock.json /usr/src/app/package-lock.json
COPY .env /usr/src/app/.env

RUN npm i npm@6.0.1 -g
RUN npm i react-scripts@1.1.1 -g
RUN npm i

CMD ["npm", "start"]
